import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_EN_US_GLORIOUS_ENGRAMMER: LayoutConfig = {
  codePoints: {
    // Backquote: "`~",
    Digit1: "1!",
    Digit2: "2@",
    Digit3: "3#",
    Digit4: "4$",
    Digit5: "5%",
    Digit6: "6^",
    Digit7: "7&",
    Digit8: "8*",
    Digit9: "9(",
    Digit0: "0)",
    // Minus: "-_",
    // Equal: "=+",
    KeyQ: "bB",
    KeyW: "yY",
    KeyE: "oO",
    KeyR: "uU",
    KeyT: `'"`,
    KeyY: ";:",
    KeyU: "lL",
    KeyI: "dD",
    KeyO: "wW",
    KeyP: "vV",
    // BracketLeft: "[{",
    // BracketRight: "]}",
    // Backslash: "\\|",
    KeyA: "cC",
    KeyS: "iI",
    KeyD: "eE",
    KeyF: "aA",
    KeyG: ",<",
    KeyH: ".>",
    KeyJ: "hH",
    KeyK: "tT",
    KeyL: "sS",
    // Semicolon: "oO",
    // Quote: `'"`,
    // IntlBackslash: "\\|",
    KeyZ: "gG",
    KeyX: "xX",
    KeyC: "jJ",
    KeyV: "kK",
    KeyB: "-_",
    KeyN: "/?",
    KeyM: "rR",
    Comma: "mM",
    Period: "fF",
    Slash: "pP",
    Space: " ",
  },
};
